server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://zmwww.xyz:3306/personal_finance_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: false